### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by carlo-dev-git** [STMicroelectronics/stm32-mw-usb-host#6]
There are many spaces before semicolons in this repository.
Please merge my pull request which contains some other minor cleanup as well.

**Comment by ALABSTM** [comment]
ST Internal Reference: 123568

**Comment by ALABSTM** [comment]
Hi @carlo-dev-git,

A cleanup of the source files has been made in the frame of version [3.4.1](https://github.com/STMicroelectronics/stm32_mw_usb_host/releases/tag/v3.4.1) of this library, released a couple of days ago.

With regards,
